AllCops:
  TargetRubyVersion: 3.2

plugins:
  - rubocop-yard
  - rubocop-md

inherit_gem:
  rubocop-shopify: rubocop.yml

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Markdown:
  Autodetect: false
